apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment-nginx
spec:
  replicas: 2 # create a replicaSet of two pods
  selector: #  through this field replicas find the pods by matching labels of app: nginx
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.1
        ports: 
        - containerPort: 80 # always the port where application is serving

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-internal
spec:
  selector: # pod label
    app: nginx
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 80
